require:
  - rubocop-md

AllCops:
  Include:
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
    - 'spec/**/*.rb'
    - 'docs/*.md'
  Exclude:
    - 'bin/**/*'
    - 'spec/dummy/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'Rakefile'
    - 'Gemfile'
    - 'README.md'
    - '*.gemspec'
    - '**/*.gemfile'
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.3

Rails:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'lib/test-prof.rb'
    - '*.md'

Style/ExpandPathArguments:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'spec/**/*.rb'

Style/AsciiComments:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*.rb'

Style/ParallelAssignment:
  Exclude:
    - 'spec/**/*'

Style/GlobalVars:
  Exclude:
    - 'spec/integrations/fixtures/**/*'
    - 'spec/bugs/fixtures/**/*'

Style/ReturnNil:
  Enabled: true
  EnforcedStyle: return

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: no_space

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Layout/EmptyLinesAroundArguments:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'lib/test_prof/cops/rspec/aggregate_failures.rb'

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Rails/Date:
  Enabled: false

Rails/TimeZone:
  Enabled: false
